import type { NextPage } from 'next';
import Head from 'next/head';
import io from 'Socket.IO-client';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
let socket;

const Home: NextPage = () => {
  const [latestValues, setLatestValues] = useState(null);
  useEffect(() => {
    socketInitializer();
  }, []);

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = io();

    socket.on('connect', () => {
      console.log('connected');
    });

    socket.on('osc', (message) => {
      console.log(message.message.args);
      setInterval(() => {
        setLatestValues(message.message.args);
      }, 1000);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Engine Signature</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Engine Signature</h1>
        <p>{JSON.stringify(latestValues)}</p>
      </main>
    </div>
  );
};

export default Home;
