import type { NextPage } from 'next';
import Head from 'next/head';
import io from 'Socket.IO-client';
import { useCallback, useEffect, useState } from 'react';
import { Switch } from '@headlessui/react';
import { ConnnectionStates } from '../local';
import ConnectionStatus from '../components/connection-status';

let socket;

const Home: NextPage = () => {
  const [latestValues, setLatestValues] = useState();
  const [socketStatus, updateSocketStatus] = useState<ConnnectionStates>('CLOSED');
  const [socketOpen, setSocketOpenn] = useState(false);

  const initiSocket = useCallback(async () => {
    await fetch('/api/socket');
    socket = io();

    socket.on('connect', () => {
      updateSocketStatus('LISTENING');
    });
    socket.on('disconnect', () => {
      updateSocketStatus('CLOSED');
    });

    socket.on('osc', (message) => {
      if (socketStatus !== 'CLOSED' && socketStatus !== 'ERROR') {
        setLatestValues(message.message.args);
      }
    });
  }, [socketStatus]);

  useEffect(() => {
    if (socketOpen) {
      initiSocket();
    } else {
      updateSocketStatus('CLOSING');
      socket = io();
      socket.emit('end');
      updateSocketStatus('CLOSED');
    }
  }, [socketOpen, initiSocket]);

  return (
    <div>
      <Head>
        <title>Engine Signature</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='font-sans text-center text-2xl p-4'>Engine Signature Detection</h1>
        <div className='grid grid-cols-2 gap-4 p-8'>
          <div className='p-4 space-y-4'>
            <h2 className='font-sans text-left text-xl'>Control Panel</h2>
            <div className='flex space-x-4'>
              <p>Connection:</p>
              <span>Off</span>{' '}
              <Switch
                checked={socketOpen}
                onChange={setSocketOpenn}
                className={`${
                  socketOpen ? 'bg-blue-600' : 'bg-gray-200'
                } relative inline-flex items-center h-6 rounded-full w-11 transition-colors ease-in-out duration-200`}
              >
                <span className='sr-only'>Connection</span>
                <span
                  className={`${
                    socketOpen ? 'translate-x-6' : 'translate-x-1'
                  } inline-block w-4 h-4 transform bg-white rounded-full transition-colors ease-in-out duration-200`}
                />
              </Switch>
              <span>On</span>
            </div>
          </div>
          <div className='p-4 space-y-4'>
            <h2 className='font-sans text-left text-xl'>Output</h2>
            <div className='flex space-x-4'>
              <p className='pt-2'>Conection Status:</p>
              <ConnectionStatus status={socketStatus} />
            </div>
            <div className='flex space-x-4'>
              <p className='pt-2'>Outputs</p>
              <span>{JSON.stringify(latestValues)}</span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
